# Site settings
title: Zetsu
email: zetsu@domain.com
description: Um lindo tema feito para jekyll e com o <3
baseurl: "/zetsu"
url: "http://nandomoreira.me"

author:
  name     : 'Fernando Moreira'
  email    : hi@nandomoreira.me
  url      : http://nandomoreira.me
  facebook : http://facebook.com/fernando.dev
  twitter  : http://twitter.com/nandomoreirame

github: https://github.com/nandomoreirame/zetsu
disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
