# Site settings
title: Afra55
email: yunomo73@163.com
description: 你好，我好，大家好！
baseurl: "http://afra55.github.io/"
url: "http://nandomoreira.me"

author:
  name     : 'Fernando Moreira'
  email    : hi@nandomoreira.me
  url      : http://nandomoreira.me
  facebook : http://facebook.com/fernando.dev
  twitter  : http://twitter.com/nandomoreirame

github: https://github.com/nandomoreirame/zetsu
disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
