# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

group :development do
  gem 'rake', '~> 10.4.2'
  gem 'sass', '~> 3.4.20'
  gem 'jekyll', '~> 3.0.1'
end
